version: '2'

services:
  oportunidades:
    tty: true
    build: ./src
    image: laravel-oportunidades:latest
    container_name: oportunidades
    volumes:
      - /home/oportuni/public_html:/app
      - /etc/pki/tls/certs:/etc/apache2/certs
      - /etc/pki/tls/private:/etc/apache2/private
    ports:
      - "8084:80"
      - "8085:443"
    restart: always
    networks: 
      default:
        ipv4_address: 172.20.0.5
networks:
  default:
    external:
      name: rede_docker