version: '2'

services:
  oportunidades:
    tty: true
    build: ./src
    image: laravel-oportunidades:latest
    container_name: oportunidades
    volumes:
      - /home/oportuni/public_html:/app
      - /etc/pki/tls/certs:/etc/apache2/certs
      - /etc/pki/tls/private:/etc/apache2/private
    ports:
      - "8084:80"
      - "8085:443"
    restart: always
    networks: 
      default:
        ipv4_address: 172.20.0.4
    depends_on:
      - database
  database:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=homestead
    networks: 
      default:
        ipv4_address: 172.20.0.5
    volumes: 
      - database
networks:
  default:
    external:
      name: rede_docker
volumes: 
  database: