version: '2'

services:
  oportunidades:
    tty: true
    build: .
    image: lucaslz/laravel-oportunidades
    container_name: oportunidades
    volumes:
      - /home/oportuni/public_html:/app
      - /etc/pki/tls/certs:/etc/apache2/certs
      - /etc/pki/tls/private:/etc/apache2/private
    ports:
      - "8084:80"
      - "8085:443"
    restart: always
    networks: 
      default:
        ipv4_address: 172.20.0.5
    depends_on:
      - postgres
  postgres:
    image: postgres:12.3
    restart: always
    container_name: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=homestead
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks: 
      default:
        ipv4_address: 172.20.0.4
networks:
  default:
    external:
      name: rede_docker